services:
  - type: web
    name: varnox-xd-v2
    env: node
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
